---
title: "TCT Reviewer Pool"
output: html_document
---

# This adjusts the width and margins of the HTML output. 
# https://stackoverflow.com/questions/34906002/increase-width-of-entire-html-rmarkdown-output

<style type="text/css">
div.main-container {
  max-width: 1200px;
  margin-left: 0;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r data}
# setwd("C:/Users/eellerton\OneDrive - SAGE Publishing/Laptop/Desktop/Reviewer dashboards/reviewerpool/WillingReviewersTCT")
# install.packages("tidyverse")
# install.packages("DT")

library(tidyverse)
library(DT)

# Import & Tidy Reviewer Data.
willingreviewers <- as_tibble(read.csv("willingreviewers.csv"))
#willingreviewers.AE <- filter(willingreviewers, Person.Attribute.Type == "Willing Article Editor")
willingreviewers <- filter(willingreviewers, Person.Attribute.Type == "Willing Reviewer")
#willingreviewers.AE$Willing.AE <- "True"
#illingreviewers.revi$Willing.Reviewer <- "True"
#willingreviewers.AE <- select(willingreviewers.AE,-c(Person.Attribute, Person.Attribute.Type))
willingreviewers <- select(willingreviewers,-c(Person.Attribute, Person.Attribute.Type))
colnames(willingreviewers) <-c("Person.ID",
                              "Salutation",
                              "Full.Name",
                              "Institution",
                              "Country.Region",
                              "Primary.E.mail.Address")




#willingreviewers <- full_join(willingreviewers.AE, willingreviewers.reviewers, by = c("Person.ID",
                                                                                      #"Salutation",
                                                                                      ##"Full.Name",
                                                                                     # "Institution",
                                                                                      #"Country.Region",
                                                                                      #"Primary.E.mail.Address"))

# Import & Tidy Reviewer Keywords.
userkeywords <- as_tibble(read.csv("userkeywords.csv"))
#userkeywords2 <- as_tibble(read.csv("userkeywords2.csv"))
#userkeywords3 <- as_tibble(read.csv("userkeywords3.csv"))
#userkeywords4 <- as_tibble(read.csv("userkeywords4.csv"))
#userkeywords5 <- as_tibble(read.csv("userkeywords5.csv"))
#userkeywords6 <- as_tibble(read.csv("userkeywords6.csv"))
#userkeywords7 <- as_tibble(read.csv("userkeywords7.csv"))
#userkeywords8 <- as_tibble(read.csv("userkeywords8.csv"))

#userkeywords <-  userkeywords1

colnames(userkeywords) <-c("Person.ID",
                            "Person.Attribute.Type",
                            "Person.Attribute")
                      
filteredkeywords <- semi_join(userkeywords, willingreviewers, by = "Person.ID")
filteredkeywords <- group_by(filteredkeywords, Person.ID)
filteredkeywords <- mutate(filteredkeywords, Keywords = paste0(Person.Attribute, sep =  ", ", collapse = "")) 
filteredkeywords <- select(filteredkeywords,-c(Person.Attribute, Person.Attribute.Type))
filteredkeywords <- distinct(filteredkeywords)

reviewerpool <- full_join(willingreviewers, filteredkeywords, by = "Person.ID")

```


```{r table}
datatable(reviewerpool, options = list(pageLength = nrow(reviewerpool), lengthChange = FALSE), rownames = FALSE)

```

